apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-header-app
  labels:
    app: flask-header-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-header-app
  template:
    metadata:
      labels:
        app: flask-header-app
    spec:
      containers:
      - name: flask-header-app
        image: <your-docker-repo>/flask-header-app:latest
        ports:
        - containerPort: 5000
